config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :friendships

  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :profiles

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profile = Profile.find(current_user)
    @profiles = Profile.where.not(user_id: current_user)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    #@profile = Profile.find(params[:id]).id
    @activities = Activity.where(profile_id: params[:id])
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.id = current_user.id
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :address, :gender, :birthday, :country, :description, :team_id, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Gender</th>
      <th>Birthday</th>
      <th>Country</th>
      <th>Description</th>
      <th>Team</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.birthday %></td>
        <td><%= profile.country %></td>
        <td><%= profile.description %></td>
        <td><%= profile.team_id %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% if !Friendship.exists?( profile: @profile, friend: profile) || !Friendship.exists?( profile: profile, friend: @profile) %>
              <%= link_to 'Request Friend', friendships_path(:friend_id => profile), method: :post %>
          <% else %>

          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>


<%if Profile.find(current_user) != @profile %>
    <h1> <%=@profile.name %> Profile </h1>
<% else %>
    <h1> My Profile </h1>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthday %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profile.description %>
</p>

<p>
  <strong>Team:</strong>
  <%= @profile.team_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<%if Profile.find(current_user) == @profile %>
    <%= link_to 'Edit', edit_profile_path(@profile) %>
<% end %>


<%= link_to 'New Activity', activity_path(@profile.id), method: :post %>

<h2> <%=@profile.name%> Activities </h2>

<ul>
  <% @activities.each do |activity| %>
    <li>
         <strong><%= activity.title %></strong>
          <%= activity.kind %>
          <%= link_to "See", activity, method: :get%>
    </li>
  <% end %>
</ul>



<h2> <%=@profile.name%> Friends </h2>

<ul style="list-style-type: none;">
  <% for friendship in @profile.friendships %>
      <%if friendship.status == "accepted" %>
          <li>
            <%= link_to friendship.friend.name, user_path(friendship.friend.id), method: :get %>
          </li>
      <%end %>
  <% end %>
</ul>