config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :friendships

  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :profiles

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :profile
  belongs_to :friend, :class_name => "Profile", :foreign_key =>"friend_id"

  validates :profile_id, presence: true
  validates :friend_id, presence: true
  validates :status, presence: true

  def self.accept(profile, friend)
        transaction do
          accept_one_side(profile, friend)
          accept_one_side(friend, profile)
    end
  end

  def self.accept_one_side(profile, friend)
    request = find_by_user_id_and_friend_id(profile, friend)
    request.status = 'accepted'
    request.save!
  end

  def self.add(profile, friend)
    if profile != friend and !find_by_profile_id_and_friend_id(profile, friend)
      transaction do
        create(:profile => profile, :friend => friend, :status => "pending")
        create(:profile => friend, :friend => profile, :profile => "requested")
      end
    end
  end

  def self.remove(profile, friend)
    transaction do
      remove_one_side(profile, friend)
      remove_one_side(friend, profile)
    end
  end

  def self.remove_one_side(profile, friend)
    request = find_by_user_id_and_friend_id(profile, friend)
    request.destroy
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @friendships = Friendship.all
    respond_with(@friendships)
  end

  def show
    #respond_with(@friendship)
  end

  def new
    #@friendship = Friendship.new
    #respond_with(@friendship)
  end

  def edit
  end

  def create
    #@friendship = Friendship.new(friendship_params)
    #@friendship.save
    #respond_with(@friendship)

    #@friend = Profile.find(params[:friend_id])
    @profile = Profile.find(current_user)
    @friend = Profile.find(params[:friend_id])
    @friendship = Friendship.add(@profile , @friend)

    if @friendship.nil?
      flash[:notice] = "Unable to add friend."
      redirect_to profile_path
    else
      flash[:error] = "Added friend."
      redirect_to home_index_path
    end
  end

  def update

    Friendship.accept(@friendship.profile, @friendship.friend)

    flash[:notice] = 'Friend sucessfully accepted!'
    redirect_to profile_path

  end

  def destroy
    Friendship.remove(@friendship.profile,@friendship.friend)
    flash[:notice] = 'Friend sucessfully removed!'
    redirect_to home_index_path

  end

  private
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    def friendship_params
      params.require(:friendship).permit(:profile_id, :friend_id, :status)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.number_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Friendships</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Friend</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.profile_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.status %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @friendship.profile_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friendship.status %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>