config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :friendships

  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :profiles

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  belongs_to :profile

  validates :profile_id, presence: true
  validates :type, presence: true
  validates :title, presence: true
  validates :profile_id, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @activities = Activity.all
    respond_with(@activities)
  end

  def show
    respond_with(@activity)
  end

  def new
    @activity = Activity.new
    respond_with(@activity)
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.profile_id = current_user.id
    @activity.save
    respond_with(@activity)
  end

  def update
    @activity.update(activity_params)
    @activity.profile_id = current_user.id
    respond_with(@activity)
  end

  def destroy
    @activity.destroy
    respond_with(@activity)
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:type, :title, :description, :startdatetime, :latstart, :longstart, :profile_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label "Type" %><br>
      <%= f.radio_button(:type, "Running") %>
      <%= label_tag(:type, "Running") %>
      <%= f.radio_button(:type, "Cycling") %>
      <%= label_tag(:type, "Cycling") %>
      <%= f.radio_button(:type, "Swimming") %>
      <%= label_tag(:type, "Swimming") %>
      <%= f.radio_button(:type, "Gymn") %>
      <%= label_tag(:type, "Gymn") %>
    </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :startdatetime %><br>
    <%= f.datetime_select :startdatetime %>
  </div>
  <div class="field">
    <%= f.label :latstart %><br>
    <%= f.text_field :latstart %>
  </div>
  <div class="field">
    <%= f.label :longstart %><br>
    <%= f.text_field :longstart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Title</th>
      <th>Description</th>
      <th>Startdatetime</th>
      <th>Latstart</th>
      <th>Longstart</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.type %></td>
        <td><%= activity.title %></td>
        <td><%= activity.description %></td>
        <td><%= activity.startdatetime %></td>
        <td><%= activity.latstart %></td>
        <td><%= activity.longstart %></td>
        <td><%= activity.profile_id %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @activity.type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Startdatetime:</strong>
  <%= @activity.startdatetime %>
</p>

<p>
  <strong>Latstart:</strong>
  <%= @activity.latstart %>
</p>

<p>
  <strong>Longstart:</strong>
  <%= @activity.longstart %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @activity.profile_id %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>