config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :friendships

  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :profiles

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UltimateActivityTracker</title>

  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/profiles">People</a></li>
        <li class="active"><a href="/friendships">Friends</a></li>
        <li class="active"><a href="/activities">Activities</a></li>

        <% if user_signed_in? %>
            <li> <%= link_to "My Profile", profile_path(Profile.find(current_user)), method: :get, :class => 'active'%> </li>
        <% end %>
      </ul>


      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to "Edit Password or Mail", edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>

    </div>
  </div>
</nav>

<div class="container">

  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>